# Generated by Django 4.2 on 2023-07-27 03:11

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('line3', models.CharField(blank=True, max_length=255)),
                ('line4', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=64)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FulfillmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref_id', models.IntegerField()),
                ('order_number', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('shipped', 'Shipped'), ('canceled', 'Canceled')], default='open', max_length=20)),
                ('shipping_method', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.location')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fulfillments.shippingaddress')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('fulfillment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fulfillments.fulfillmentorder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.product')),
            ],
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=255)),
                ('carrier', models.CharField(choices=[('dhl_ecommerce', 'DHL Ecommerce'), ('fedex', 'FedEx'), ('ups', 'UPS'), ('usps', 'USPS'), ('other', 'Other')], default='dhl_ecommerce', max_length=50)),
                ('carrier_other_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fulfillment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fulfillments.fulfillmentorder')),
            ],
        ),
    ]
